-- Seed: tareas iniciales de Limpieza (Cocina y Barra)
INSERT INTO "LimpiezaTask" ("id", "name", "section", "order", "active", "createdAt") VALUES
  ('seed-cocina-01', 'Freidora grande', 'COCINA', 0, true, NOW()),
  ('seed-cocina-02', 'Campana', 'COCINA', 1, true, NOW()),
  ('seed-cocina-03', 'Mover horno', 'COCINA', 2, true, NOW()),
  ('seed-cocina-04', 'Mover freidora', 'COCINA', 3, true, NOW()),
  ('seed-cocina-05', 'Freidora chica por dentro', 'COCINA', 4, true, NOW()),
  ('seed-cocina-06', 'Mover mueble basura', 'COCINA', 5, true, NOW()),
  ('seed-cocina-07', 'Mover nevera chica', 'COCINA', 6, true, NOW()),
  ('seed-cocina-08', 'Mover congelador', 'COCINA', 7, true, NOW()),
  ('seed-cocina-09', 'Mover lavavajillas', 'COCINA', 8, true, NOW()),
  ('seed-cocina-10', 'Estantería chica y grande', 'COCINA', 9, true, NOW()),
  ('seed-cocina-11', 'Envasadora', 'COCINA', 10, true, NOW()),
  ('seed-cocina-12', 'Esquina sushi', 'COCINA', 11, true, NOW()),
  ('seed-cocina-13', 'Limpiar neveras grande y chica', 'COCINA', 12, true, NOW()),
  ('seed-cocina-14', 'Limpiar debajo de los hornos', 'COCINA', 13, true, NOW()),
  ('seed-cocina-15', 'Paredes', 'COCINA', 14, true, NOW()),
  ('seed-cocina-16', 'Suelo con lejía y cepillo', 'COCINA', 15, true, NOW()),
  ('seed-cocina-17', 'Estantería platos', 'COCINA', 16, true, NOW()),
  ('seed-cocina-18', 'Puertas de los hornos', 'COCINA', 17, true, NOW()),
  ('seed-cocina-19', 'Congelador por dentro', 'COCINA', 18, true, NOW()),
  ('seed-cocina-20', 'Estantería de microondas', 'COCINA', 19, true, NOW()),
  ('seed-cocina-21', 'Estantería de especias', 'COCINA', 20, true, NOW()),

  ('seed-barra-01', 'Cristales entrada', 'BARRA', 0, true, NOW()),
  ('seed-barra-02', 'Cava grande', 'BARRA', 1, true, NOW()),
  ('seed-barra-03', 'Dispensador tinto', 'BARRA', 2, true, NOW()),
  ('seed-barra-04', 'Dispensador tinto mover', 'BARRA', 3, true, NOW()),
  ('seed-barra-05', 'Mueble grande TV / Televisor', 'BARRA', 4, true, NOW()),
  ('seed-barra-06', 'Polvo cava grande', 'BARRA', 5, true, NOW()),
  ('seed-barra-07', 'Mueble botellas', 'BARRA', 6, true, NOW()),
  ('seed-barra-08', 'Persiana interior/exterior', 'BARRA', 7, true, NOW()),
  ('seed-barra-09', 'Lámparas, bombillas, cuernos', 'BARRA', 8, true, NOW()),
  ('seed-barra-10', 'Lavavajillas', 'BARRA', 9, true, NOW()),
  ('seed-barra-11', 'Mueble acero, cubiertos', 'BARRA', 10, true, NOW()),
  ('seed-barra-12', 'Mesas y sillas interior', 'BARRA', 11, true, NOW()),
  ('seed-barra-13', 'Mesas y sillas exterior', 'BARRA', 12, true, NOW()),
  ('seed-barra-14', 'Nevera cafetera, mover', 'BARRA', 13, true, NOW()),
  ('seed-barra-15', 'Nevera vasos fríos, mover', 'BARRA', 14, true, NOW()),
  ('seed-barra-16', 'Nevera Coca-Cola, mover', 'BARRA', 15, true, NOW()),
  ('seed-barra-17', 'Cuadro eléctrico, extintores', 'BARRA', 16, true, NOW()),
  ('seed-barra-18', 'Cajas madera techo plumero', 'BARRA', 17, true, NOW()),
  ('seed-barra-19', 'Cubos de pan', 'BARRA', 18, true, NOW()),
  ('seed-barra-20', 'Extractor salón', 'BARRA', 19, true, NOW()),
  ('seed-barra-21', 'Paredes, baño, comedor', 'BARRA', 20, true, NOW()),
  ('seed-barra-22', 'Toldos laterales', 'BARRA', 21, true, NOW()),
  ('seed-barra-23', 'Nevera carne por dentro', 'BARRA', 22, true, NOW()),
  ('seed-barra-24', 'Nevera vasos fríos por dentro', 'BARRA', 23, true, NOW()),
  ('seed-barra-25', 'Máquina cerveza mover', 'BARRA', 24, true, NOW()),
  ('seed-barra-26', 'Estantería encima de jamón', 'BARRA', 25, true, NOW()),
  ('seed-barra-27', 'Máquina agua mover', 'BARRA', 26, true, NOW()),
  ('seed-barra-28', 'Toldo grande y automático', 'BARRA', 27, true, NOW()),
  ('seed-barra-29', 'Nevera Coca-Cola por dentro', 'BARRA', 28, true, NOW()),
  ('seed-barra-30', 'Puerta botellas vino', 'BARRA', 29, true, NOW()),
  ('seed-barra-31', 'Máquina café mover', 'BARRA', 30, true, NOW()),
  ('seed-barra-32', 'Nevera carne madurada', 'BARRA', 31, true, NOW()),
  ('seed-barra-33', 'Todas las copas colgadas', 'BARRA', 32, true, NOW()),
  ('seed-barra-34', 'Almacén del baño grande', 'BARRA', 33, true, NOW()),
  ('seed-barra-35', 'Suelo de la terraza', 'BARRA', 34, true, NOW()),
  ('seed-barra-36', 'Sillas de la barra', 'BARRA', 35, true, NOW()),
  ('seed-barra-37', 'Cubo de fregona y recogedor', 'BARRA', 36, true, NOW()),
  ('seed-barra-38', 'Plantas de los laterales', 'BARRA', 37, true, NOW()),
  ('seed-barra-39', 'Carrito de jamón y platos', 'BARRA', 38, true, NOW())

ON CONFLICT ("id") DO NOTHING;
